name: TrackPe BE CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: [self-hosted, trackpe-prod]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Image
        run: |
          echo "Building image"
          ./build_docker.sh

  test:
    runs-on: [self-hosted, trackpe-prod]
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test Image
        run: |
          echo "Testing image"
          ./docker_run_test_cases.sh

  push:
    runs-on: [self-hosted, trackpe-prod]
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY_URI }}

      - name: Push Image
        run: |
          echo "Push image"
          docker tag trackpe-core:latest ${{ secrets.ECR_REGISTRY_URI }}:$(date -u +"%Y%m%d")-${{ github.sha }}
          docker push ${{ secrets.ECR_REGISTRY_URI }}:$(date -u +"%Y%m%d")-${{ github.sha }}

  deploy_prod:
    runs-on: [self-hosted, trackpe-prod]
    needs: push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Prod
        run: |
          echo "Deploying to Prod server"
          ~/deploy_server.sh
          echo "Deployment completed.."
